### ISSUE TITLE
How custom toolbar?

### ISSUE THREAD

**Issue by eritondev-stack** [simonkellly/deckbrowser-css#1]
Hello, how are you?

How do I custom toolbar? For example?

![image](https://user-images.githubusercontent.com/58184733/196212809-45846fe2-9279-4fd5-8038-f7ad2042ff45.png)

**Comment by simonkellly** [comment]
Hello, I have just pushed an update v1.0.1 which should add support for this! let me know if you have any issues

**Comment by eritondev-stack** [comment]
Thanks for updating new version!!! 

Future update, add support **toolbar-bottom.css**

**Comment by eritondev-stack** [comment]
> Hello, I have just pushed an update v1.0.1 which should add support for this! let me know if you have any issues

Thanks for updating new version!!!

Future update, add support toolbar-bottom.css
