### ISSUE TITLE
How Custom Buttons?

### ISSUE THREAD

**Issue by cjdduarte** [simonkellly/deckbrowser-css#2]
How Custom Buttons in Anki 2.1.55+?

![image](https://user-images.githubusercontent.com/42243532/208397240-61b4921a-c252-4608-9159-cc335bcf40c9.png)

![image](https://user-images.githubusercontent.com/42243532/208397095-4942c70b-cbb2-4b09-bc54-f104e587fd57.png)

**Comment by simonkellly** [comment]
Hello,
Unfortunatly this addon currently only supports the top toolbar and main deckbrowser window modifcations. I do not personally have plans to change this as I am staying on v2.1.54.
